---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-example
spec:
  selector:
    matchLabels:
      app: myapp-nginx
  replicas: 3
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: myapp-nginx
    spec:
      containers:
      - name: nginx
        image: 192.168.1.100:5000/myos:nginx
        ports:
        - protocol: TCP
          containerPort: 80
      restartPolicy: Always
