---
apiVersion: v1
kind: Service
metadata:
  name: test-service
spec:
  selector:
    app: myapache
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  clusterIP:
  externalIPs:
  - 192.168.1.101
  type: LoadBalancer
