---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-example
spec:
  selector:
    matchLabels:
      app: myapp-web
  replicas: 3
  #revisionHistoryLimit: 10
  #strategy:
  #  rollingUpdate:
  #    maxSurge: 25%
  #    maxUnavailable: 25%
  #  type: RollingUpdate
  template:
    metadata:
      labels:
        app: myapp-web
    spec:
      #nodeName: node-0001
      #nodeSelector:
      #  disktype: ssd
      #affinity:
      #  podAffinity:
      #    requiredDuringSchedulingIgnoredDuringExecution:
      #    - labelSelector:
      #        matchExpressions:
      #        - key: app
      #          operator: In
      #          values:
      #          - myapp-php
      #      topologyKey: kubernetes.io/hostname
      #  podAntiAffinity:
      #    preferredDuringSchedulingIgnoredDuringExecution:
      #    - weight: 1
      #      podAffinityTerm:
      #        labelSelector:
      #          matchExpressions:
      #          - key: app
      #            operator: In
      #            values:
      #            - myapp-apache
      #        topologyKey: kubernetes.io/hostname
      containers:
      - name: nginx
        image: 192.168.1.100:5000/myos:nginx
        ports:
        - protocol: TCP
          containerPort: 80
      restartPolicy: Always
